### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by vmbrasseur** [portland-startups/docs#65]
Hello!

Without a license telling people what permissions they have to use the copyrighted works in this repository, the works are automatically _All Rights Reseerved_. They are available to look at, but not to use, modify, or redistribute.

Because these are texts, I recommend [Creative Commons (CC)](http://creativecommons.org) licenses. Of the available CC licenses, I recommend [CC0](https://creativecommons.org/publicdomain/zero/1.0/) if you don't want to require attribution to the copyright holders (contributors) or [CC BY](https://creativecommons.org/licenses/by/4.0/) if you would like that attribution. Of course, other CC options are available. If you'd prefer to investigate those, you can see them all [on the CC website](https://creativecommons.org/about/cclicenses/).

**Comment by turoczy** [comment]
Great point! Thank you @vmbrasseur

**Comment by turoczy** [comment]
Added! https://github.com/portland-startups/docs/pull/66
